config/routes.rb
Rails.application.routes.draw do

  # дергаем спец. девайзовский метод, который генерит все нужные ему пути
  devise_for :users

  root "events#index"

  resources :events do
    # вложенный ресурс комментов
    resources :comments, only: [:create, :destroy]

    # вложенный ресурс подписок (см. rake routes)
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
# (с) goodprogrammer.ru
#
# Модель Пользователя
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  # Юзер может создавать много событий
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  has_many :events

  validates :name, presence: true, length: {maximum: 35}

  validates :email, presence: true, length: {maximum: 255}
  validates :email, uniqueness: true
  validates :email, format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  private

  def set_name
    self.name = "Товарисч №#{rand(777)}" if self.name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email)
      .update_all(user_id: self.id)
  end
end

app/controllers/users_controller.rb
# (с) goodprogrammer.ru
#
# Контроллер, управляющий пользователями
class UsersController < ApplicationController
  # Встроенный в девайз фильтр — посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show]

  # Задаем объект @user для шаблонов и экшенов
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>

    <p class="buffer-top">
      <%# Ссылка на смену пароля текущего залогиненного юзера (этот путь %>
      <%# генерит девайз) %>
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top"><%= link_to 'Редактировать профиль',
      edit_user_path(@user), class: 'btn btn-default' %></p>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
        <h3>Организовал:</h3>
        <div class="row">
          <%= render partial: 'events/event', collection: @user.events %>
        </div>
      <% else %>
        <p class="buffer-top">Пользователь пока не организовал ни одного
          события</p>
      <% end %>
    </div>
  </div>
</div>